version: '3'

services:
  # MongoDB for metadata storage
  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27019:27017"
    restart: unless-stopped

  # Unpub server
  unpub:
    image: dart:stable
    working_dir: /app
    ports:
      - "24000:4000"
    volumes:
      - ./unpub:/app/unpub
      - ./package_storage:/app/unpub-packages
    # environment:
    #   - MONGO_URL=mongodb://mongodb:27017/dart_pub
    #   - UPLOADER_TOKEN=89dsfl8s091212
    #   - UPLOADER_EMAIL=doanthanhduong11031990@gmail.com
    depends_on:
      - mongodb
    command: >
      bash -c "
        cd /app/unpub &&
        dart pub get &&
        dart bin/unpub.dart --directory=/app/unpub-packages --database=mongodb://mongodb:27017/dart_pub --uploader-token=89dsfl8s091212 --uploader-email=doanthanhduong11031990@gmail.com
      "
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local