version: '3'

services:
  # MongoDB for metadata storage
  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    ports:
      - "37019:27017"
    restart: unless-stopped

  # Unpub server
  unpub:
    image: dart:stable
    working_dir: /app
    ports:
      - "34000:4000"
    volumes:
      - ./unpub:/app/unpub
      - ./package_storage:/app/unpub-packages
    environment:
      - UNPUB_HOST=0.0.0.0
      - UNPUB_PORT=4000
      - UNPUB_MONGO_DB=mongodb://mongodb:27017/dart_unpub
      - UPLOADER_TOKEN=89dsfl8s091212
      - VIEW_TOKEN=69askl909j0DLk009FDJOM
      - UPLOADER_EMAIL=developer@masterisehomes.com
      - AWS_S3_BUCKET_NAME=mh-mobile-test-bucket
      - AWS_S3_ENDPOINT=s3.amazonaws.com
      - AWS_DEFAULT_REGION=ap-southeast-1
      - AWS_ACCESS_KEY_ID=???
      - AWS_SECRET_ACCESS_KEY=???

    depends_on:
      - mongodb
    command: >
      bash -c "
        cd /app/unpub &&
        dart pub get &&
        dart bin/unpub_s3.dart
      "
    restart: unless-stopped

  nginx:
    container_name: nginx_proxy
    image: nginx:latest
    ports:
      - "8880:80"
      - "443:443"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/certs:/etc/nginx/certs:ro
    depends_on:
      - unpub
    restart: always
volumes:
  mongodb_data:
    driver: local